export const iphone14Series = [
  {
    id: "iphone-14",
    name: "iPhone 14",
    description:
      "The essential iPhone with solid performance and improved battery life.",
    colors: [
      {
        name: "Blue",
        hex: "#337099",
        image: "/Images/Apple/Phone/BlueiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/BlueiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/BlueiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/BlueiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/BlueiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Purple",
        hex: "#8C61B7",
        image: "/Images/Apple/Phone/PurpleiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/PurpleiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/PurpleiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/PurpleiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/PurpleiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Midnight",
        hex: "#141D29",
        image: "/Images/Apple/Phone/MidnightiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/MidnightiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/MidnightiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/MidnightiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/MidnightiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Starlight",
        hex: "#FEFBF2",
        image: "/Images/Apple/Phone/StarlightiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/StarlightiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/StarlightiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/StarlightiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/StarlightiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Red",
        hex: "#A31111",
        image: "/Images/Apple/Phone/RediPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/RediPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/RediPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/RediPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/RediPhone14andPlusSide.png",
        ],
      },
      {
        name: "Yellow",
        hex: "#FEECA2",
        image: "/Images/Apple/Phone/YellowiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/YellowiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/YellowiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/YellowiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/YellowiPhone14andPlusSide.png",
        ],
      },
    ],
    memoryOptions: [
      {
        size: "128GB",
        price: 799,
      },
      {
        size: "256GB",
        price: 899,
      },
      {
        size: "512GB",
        price: 1099,
      },
    ],
    batteryCapacity: "3279mAh",
    frontCamera: "12MP",
    mainCamera: "12MP Wide + 12MP Ultra Wide",
    cores: 6,
    screenDiagonal: "6.1 inches",
    screenResolution: "2532 x 1170 pixels",
    refreshRate: "60Hz",
    pixelDensity: "460 ppi",
    screenType: "Super Retina XDR OLED",
    additionally: [
      "Face ID",
      "Emergency SOS via satellite",
      "Crash Detection",
      "MagSafe",
    ],
    cpu: "A15 Bionic chip (5-core GPU)",
  },
  {
    id: "iphone-14-plus",
    name: "iPhone 14 Plus",
    description:
      "Big-screen iPhone with better battery and all the core features.",
    colors: [
      {
        name: "Blue",
        hex: "#337099",
        image: "/Images/Apple/Phone/BlueiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/BlueiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/BlueiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/BlueiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/BlueiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Purple",
        hex: "#8C61B7",
        image: "/Images/Apple/Phone/PurpleiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/PurpleiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/PurpleiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/PurpleiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/PurpleiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Midnight",
        hex: "#141D29",
        image: "/Images/Apple/Phone/MidnightiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/MidnightiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/MidnightiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/MidnightiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/MidnightiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Starlight",
        hex: "#FEFBF2",
        image: "/Images/Apple/Phone/StarlightiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/StarlightiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/StarlightiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/StarlightiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/StarlightiPhone14andPlusSide.png",
        ],
      },
      {
        name: "Red",
        hex: "#A31111",
        image: "/Images/Apple/Phone/RediPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/RediPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/RediPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/RediPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/RediPhone14andPlusSide.png",
        ],
      },
      {
        name: "Yellow",
        hex: "#FEECA2",
        image: "/Images/Apple/Phone/YellowiPhone14andPlus.png",
        images: [
          "/Images/Apple/Phone/YellowiPhone14andPlus.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/YellowiPhone14andPlusFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/YellowiPhone14andPlusBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/YellowiPhone14andPlusSide.png",
        ],
      },
    ],
    memoryOptions: [
      {
        size: "128GB",
        price: 899,
      },
      {
        size: "256GB",
        price: 999,
      },
      {
        size: "512GB",
        price: 1199,
      },
    ],
    batteryCapacity: "4323mAh",
    frontCamera: "12MP",
    mainCamera: "12MP Wide + 12MP Ultra Wide",
    cores: 6,
    screenDiagonal: "6.7 inches",
    screenResolution: "2778 x 1284 pixels",
    refreshRate: "60Hz",
    pixelDensity: "458 ppi",
    screenType: "Super Retina XDR OLED",
    additionally: [
      "Face ID",
      "Emergency SOS via satellite",
      "Crash Detection",
      "MagSafe",
    ],
    cpu: "A15 Bionic chip (5-core GPU)",
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    description: "Powerful camera, Dynamic Island, and ProMotion display.",
    colors: [
      {
        name: "Deep Purple",
        hex: "#372E3B",
        image: "/Images/Apple/Phone/DeepPurpleiPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/DeepPurpleiPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/DeepPurpleiPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/DeepPurpleiPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/DeepPurpleiPhone14ProandMaxSide.png",
        ],
      },
      {
        name: "Gold",
        hex: "#F4E5CC",
        image: "/Images/Apple/Phone/GoldiPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/GoldiPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/GoldiPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/GoldiPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/GoldiPhone14ProandMaxSide.png",
        ],
      },
      {
        name: "Silver",
        hex: "#EDF0EF",
        image: "/Images/Apple/Phone/SilveriPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/SilveriPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SilveriPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SilveriPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SilveriPhone14ProandMaxSide.png",
        ],
      },
      {
        name: "Space Black",
        hex: "#1C1C1E",
        image: "/Images/Apple/Phone/SpaceBlackiPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/SpaceBlackiPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SpaceBlackiPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SpaceBlackiPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SpaceBlackiPhone14ProandMaxSide.png",
        ],
      },
    ],
    memoryOptions: [
      {
        size: "128GB",
        price: 999,
      },
      {
        size: "256GB",
        price: 1099,
      },
      {
        size: "512GB",
        price: 1299,
      },
      {
        size: "1TB",
        price: 1499,
      },
    ],
    batteryCapacity: "3200mAh",
    frontCamera: "12MP",
    mainCamera: "48MP Wide + 12MP Ultra Wide + 12MP Telephoto",
    cores: 6,
    screenDiagonal: "6.1 inches",
    screenResolution: "2556 x 1179 pixels",
    refreshRate: "120Hz",
    pixelDensity: "460 ppi",
    screenType: "Super Retina XDR OLED (ProMotion, Dynamic Island)",
    additionally: ["Face ID", "Always-On Display", "ProRAW", "MagSafe"],
    cpu: "A16 Bionic chip",
  },
  {
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    description:
      "The ultimate iPhone with biggest screen and best battery life.",
    colors: [
      {
        name: "Deep Purple",
        hex: "#372E3B",
        image: "/Images/Apple/Phone/DeepPurpleiPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/DeepPurpleiPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/DeepPurpleiPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/DeepPurpleiPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/DeepPurpleiPhone14ProandMaxSide.png",
        ],
      },
      {
        name: "Gold",
        hex: "#F4E5CC",
        image: "/Images/Apple/Phone/GoldiPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/GoldiPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/GoldiPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/GoldiPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/GoldiPhone14ProandMaxSide.png",
        ],
      },
      {
        name: "Silver",
        hex: "#EDF0EF",
        image: "/Images/Apple/Phone/SilveriPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/SilveriPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SilveriPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SilveriPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SilveriPhone14ProandMaxSide.png",
        ],
      },
      {
        name: "Space Black",
        hex: "#1C1C1E",
        image: "/Images/Apple/Phone/SpaceBlackiPhone14ProandMax.png",
        images: [
          "/Images/Apple/Phone/SpaceBlackiPhone14ProandMax.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SpaceBlackiPhone14ProandMaxFront.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SpaceBlackiPhone14ProandMaxBack.png",
          "/Images/Apple/Phone/iPhone14DisplaySide/SpaceBlackiPhone14ProandMaxSide.png",
        ],
      },
    ],
    memoryOptions: [
      {
        size: "128GB",
        price: 1099,
      },
      {
        size: "256GB",
        price: 1199,
      },
      {
        size: "512GB",
        price: 1399,
      },
      {
        size: "1TB",
        price: 1599,
      },
    ],
    batteryCapacity: "4323mAh",
    frontCamera: "12MP",
    mainCamera: "48MP Wide + 12MP Ultra Wide + 12MP Telephoto",
    cores: 6,
    screenDiagonal: "6.7 inches",
    screenResolution: "2796 x 1290 pixels",
    refreshRate: "120Hz",
    pixelDensity: "460 ppi",
    screenType: "Super Retina XDR OLED (ProMotion, Dynamic Island)",
    additionally: ["Face ID", "Always-On Display", "ProRAW", "MagSafe"],
    cpu: "A16 Bionic chip",
  },
];
